CREATE TABLE texts (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	link VARCHAR(2000) UNIQUE,
	file VARCHAR(255) UNIQUE,
	words_count INTEGER NOT NULL,
	CHECK(link IS NOT NULL OR file IS NOT NULL)
);

CREATE TABLE words (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	word VARCHAR(100) NOT NULL
);

CREATE TABLE tags (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_text INTEGER NOT NULL,
	id_word INTEGER NOT NULL,
	mark INTEGER NOT NULL,
	FOREIGN KEY(id_text) REFERENCES texts(id),
	FOREIGN KEY(id_word) REFERENCES words(id)
);
