#!/bin/sh

# Set these paths appropriately

BIN=/home/misao/BDM/text_test/bin
CMD=/home/misao/BDM/text_test/cmd
LIB=/home/misao/BDM/text_test/lib

OPTIONS="-token -lemma -sgml"

TAGGER=${BIN}/tree-tagger
TOKENIZER=${CMD}/utf8-tokenize.perl
ABBR_LIST=${LIB}/dutch-abbreviations
PARFILE=${LIB}/dutch-utf8.par

$TOKENIZER -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
