#!/bin/sh

# Set these paths appropriately

BIN=/home/misao/BDM/text_test/bin
CMD=/home/misao/BDM/text_test/cmd
LIB=/home/misao/BDM/text_test/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/italian-abbreviations
PARFILE=${LIB}/italian-utf8.par

$TOKENIZER -i -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
