#!/bin/sh

# Set these paths appropriately

BIN=/home/misao/BDM/text_test/bin
CMD=/home/misao/BDM/text_test/cmd
LIB=/home/misao/BDM/text_test/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/tokenize.pl
MWL=${CMD}/mwl-lookup-greek.perl
TAGGER=${BIN}/tree-tagger
PARFILE=${LIB}/greek.par

$TOKENIZER $* |
# recognition of MWLs
$MWL |
# tagging
$TAGGER $OPTIONS $PARFILE

